### ISSUE TITLE
Create GromacsMDProtocolSettings

### ISSUE THREAD

**Issue by hannahbaumann** [OpenFreeEnergy/openfe-gromacs#3]

**Comment by hannahbaumann** [comment]
We need different settings:
- OpenMM settings for creating the system: e.g. forcefield settings, integrator settings, thermo settings
- Gromacs MDP settings: these are the settings that will be converted to .mdp files
- Gromacs run settings: e.g. number of threads,...

Should this all be separate settings classes?

**Comment by jameseastwood** [comment]
Reviewed on 13 Aug, @hannahbaumann will make changes.
