### ISSUE TITLE
`mdout.mdp` is being written outside of `shared` and `scratch` directories.

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/openfe-gromacs#53]
Running the notebook, I get an errand `mdout.mdp` file (probably from grompp?).

**Comment by hannahbaumann** [comment]
It looks like grompp always outputs this and it looks useful as it also contains settings that were not directly specified by the user but populated with the Gromacs defaults. Therefore, I decided to add it as an output to the respective output_settings in PR #47
